site_name: "Test example"
repo_url: 'https://example.com/level1'
edit_uri: 'edit/docs'

nav:
  - Top: index.md
  - Level 1:
    - Level 1: level1/index.md
    - Level 2: '!include projects/level2/mkdocs.yml'

theme:
  name: 'material'
  features:
    - content.action.edit
    - content.action.view

plugins:
  - monorepo
